// src/app/explorer/components/all-transactions/all-transactions.component.ts
import { Component, OnInit, ViewChild, HostListener, AfterViewInit, ChangeDetectorRef, Input, EventEmitter, Output } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { first } from 'rxjs/operators';
import { MdbTablePaginationComponent, MdbTableService } from 'ng-uikit-pro-standard';
import { Angular5Csv } from 'angular5-csv/Angular5-csv';
import { BlockUI, NgBlockUI } from 'ng-block-ui';
import { MosaicId, Transaction, Address, TransactionType, BlockInfo, Deadline } from 'proximax-nem2-sdk';
import { AppConfig } from '../../../config/app.config';
import { NemProvider } from '../../../shared/services/nem.provider';
import { NodeService } from '../../../dashboard/services/node.service';
import { SharedService } from '../../../shared';


@Component({
  selector: 'app-all-transactions',
  templateUrl: './all-transactions.component.html',
  styleUrls: ['./all-transactions.component.scss']
})
export class AllTransactionsComponent implements OnInit, AfterViewInit {

  @Input() blockInfo = [];
  @BlockUI() blockUI: NgBlockUI;
  @ViewChild(MdbTablePaginationComponent) mdbTablePagination: MdbTablePaginationComponent;
  @Output() getMoreTransaction = new EventEmitter();

  linkRoute = {
    explorerAccount: {
      'link': `/${AppConfig.routes.explorerAccount.split(':')[0]}`
    },
    explorerBlock: {
      'link': `/${AppConfig.routes.explorerBlock.split(':')[0]}`
    }
  };
  firstItemIndex;
  lastItemIndex;
  previous: any;
  searchText: string;
  headElements = ['Block Height', 'Timestamp', 'Harvester/Forger', 'Number of Transactions', 'Difficulty', 'Fees', 'Export CSV'];
  options = {
    showLabels: true,
    showTitle: false,
    useBom: true,
    noDownload: false,
    headers: ['Block Height', 'Address', 'Harvester/Forger', 'Difficulty', 'Signature', 'Fees', 'Hash', 'Network type', 'Date']
  };

  constructor(
    private tableService: MdbTableService,
    private cdRef: ChangeDetectorRef
  ) {

  }

  @HostListener('input') oninput() {
    this.mdbTablePagination.searchText = this.searchText;
  }

  ngOnInit() {

    this.tableService.setDataSource(this.blockInfo);
    this.blockInfo = this.tableService.getDataSource();
    this.previous = this.tableService.getDataSource();
  }

  ngAfterViewInit() {
    this.mdbTablePagination.setMaxVisibleItemsNumberTo(10);
    this.firstItemIndex = this.mdbTablePagination.firstItemIndex;
    this.lastItemIndex = this.mdbTablePagination.lastItemIndex;

    this.mdbTablePagination.calculateFirstItemIndex();
    this.mdbTablePagination.calculateLastItemIndex();
    this.cdRef.detectChanges();
  }

  onNextPageClick(data: any) {
    this.firstItemIndex = data.first;
    this.lastItemIndex = data.last;
    if (this.mdbTablePagination.lastVisibleItemIndex === this.mdbTablePagination.allItemsLength) {
      this.getMoreTransaction.emit(this.blockInfo);
    }
  }

  onPreviousPageClick(data: any) {
    this.firstItemIndex = data.first;
    this.lastItemIndex = data.last;
  }

  exportCSV(blockH) {
    console.log('blockH', blockH);
    const data = [];
    if (blockH.toString() === '00') {
      blockH = 'all';
      this.blockInfo.forEach(element => {
        data.push(
          {
            'blockH': element.height.lower,
            'address': element.signer.address.pretty(),
            'harvester': element.signer.publicKey,
            'difficulty': element.difficulty.compact(),
            'signature': element.signature,
            'fees': element.totalFee.compact(),
            'hash': element.hash,
            'networkType': element.networkType,
            'date': element.date
          }
        );
      });
    } else {
      const array = this.blockInfo.find(element => element.height.lower === blockH);
      data.push({
        'blockH': array.height.lower,
        'address': array.signer.address.pretty(),
        'harvester': array.signer.publicKey,
        'difficulty': array.difficulty.compact(),
        'signature': array.signature,
        'fees': array.totalFee.compact(),
        'hash': array.hash,
        'networkType': array.networkType,
        'date': array.date
      });
    }
    const csv = new Angular5Csv(data, `Info block ${blockH}`, this.options);
  }
}

<div class="table-responsive table-striped">
  <table mdbTable id="tablePreview" class="table table-hover table-bordered table-striped table-sm z-depth-0">
    <thead>
      <tr>
        <th *ngFor="let head of headElements; let i = index" scope="col" class="text-center">{{head}}
        </th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let item of blockInfo; let i = index">
        <th class="font-size-08rem text-center th-sm" *ngIf="i+1 >= firstItemIndex && i < lastItemIndex">
          <span class="font-size-08rem">
              <a class="text-link mouse-pointer" [routerLink]="[linkRoute.explorerBlock.link, item.height.lower]">{{item.height.lower}}</a>
            </span>
        </th>
        <td class="text-align-center th-lg" *ngIf="i+1 >= firstItemIndex && i < lastItemIndex">{{item.date}}</td>
        <td class="font-size-08rem text-center th-lg" *ngIf="i+1 >= firstItemIndex && i < lastItemIndex">
          <span class="font-size-08rem">
            <a class="text-link mouse-pointer" [routerLink]="[linkRoute.explorerAccount.link, item.signer.address['address']]">{{item.signer.publicKey}}</a>
          </span>
        </td>

        <td class="font-size-08rem text-center th-lg" *ngIf="i+1 >= firstItemIndex && i < lastItemIndex">{{item.numTransactions}}</td>
        <td class="font-size-08rem text-center th-lg" *ngIf="i+1 >= firstItemIndex && i < lastItemIndex">{{item.difficulty.compact()}}</td>
        <td class="font-size-08rem text-center th-lg" *ngIf="i+1 >= firstItemIndex && i < lastItemIndex">{{item.totalFee.compact()}}</td>
        <td class="font-size-08rem text-align-center th-lg mouse-pointer" *ngIf="i+1 >= firstItemIndex && i < lastItemIndex" (click)="exportCSV(item.height.lower);">
          <i style="font-size: 18px; color: #118a81;" class="fa fa-download" aria-hidden="true"></i>
        </td>
      </tr>
    </tbody>
    <tfoot class="background-gris w-100">
      <tr>
        <td colspan="6">
          <mdb-table-pagination (nextPageClick)="onNextPageClick($event)" (previousPageClick)="onPreviousPageClick($event)">
          </mdb-table-pagination>
        </td>
      </tr>
    </tfoot>
  </table>
</div>

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
  <a class="btn-floating btn-large background-theme-origin waves-light" mdbWavesEffect (click)="exportCSV('00')">
    <i class="fa fa-download"></i>
  </a>
</div>

// src/components/explorer/views/allTransactions.vue
<template>
  <mdb-tbl striped responsiveXl responsiveLg responsiveMd responsiveSm>
    <mdb-tbl-head class="background-explorer" textWhite>
      <tr>
        <th v-for="(head, index) in headElements" :key="index" class="text-center">{{head}}</th>
      </tr>
    </mdb-tbl-head>
    <mdb-tbl-body>
      <tr v-for="(item, i) in blockInfo" :key="i">
        <th class="font-size-08rem text-center th-sm" v-if="i+1 >= firstItemIndex && i < lastItemIndex">
          <span class="font-size-08rem">
            <router-link v-bind:to="`/block-info/${item.height.lower}`" class="text-link mouse-pointer">{{item.height.lower}}</router-link>
              <!-- <a class="text-link mouse-pointer"></a> -->
          </span>
        </th>
        <td class="text-center th-lg" v-if="i+1 >= firstItemIndex && i < lastItemIndex">{{item.date}}</td>
        <td class="font-size-08rem text-center th-lg" v-if="i+1 >= firstItemIndex && i < lastItemIndex">
          <span class="font-size-08rem">
            <router-link :to="`/account-info/${item.signer.address['address']}`" :address="item.signer.address" class="text-link mouse-pointer">{{item.signer.publicKey}}</router-link>
          </span>
        </td>

        <td class="font-size-08rem text-center th-lg" v-if="i+1 >= firstItemIndex && i < lastItemIndex">{{item.numTransactions}}</td>
        <td class="font-size-08rem text-center th-lg" v-if="i+1 >= firstItemIndex && i < lastItemIndex">{{item.difficulty.compact()}}</td>
        <td class="font-size-08rem text-center th-lg" v-if="i+1 >= firstItemIndex && i < lastItemIndex">{{item.totalFee.compact()}}</td>
        <td class="font-size-08rem text-center th-lg mouse-pointer" v-if="i+1 >= firstItemIndex && i < lastItemIndex">
          <i style="font-size: 18px; color: #118a81;" class="fa fa-download" aria-hidden="true"></i>
        </td>
      </tr>
    </mdb-tbl-body>
    <!-- <mdb-pagination circle>
      <mdb-page-item disabled>First</mdb-page-item>
      <mdb-page-nav prev disabled></mdb-page-nav>
      <mdb-page-item active>1</mdb-page-item>
      <mdb-page-item>2</mdb-page-item>
      <mdb-page-item>3</mdb-page-item>
      <mdb-page-item>4</mdb-page-item>
      <mdb-page-item>5</mdb-page-item>
      <mdb-page-nav next></mdb-page-nav>
      <mdb-page-item>Last</mdb-page-item>
    </mdb-pagination> -->
  </mdb-tbl>
</template>

<script>
import Service from '@/services/Service'
import { Deadline, BlockInfo } from 'proximax-nem2-sdk'
import { mdbTbl, mdbTblHead, mdbTblBody, mdbPagination, mdbPageItem, mdbPageNav } from 'mdbvue';

const _service = new Service()

export default {
  name: 'allTransactions',
  components: {
    mdbTbl,
    mdbTblHead,
    mdbTblBody,
    mdbPagination,
    mdbPageItem,
    mdbPageNav
  },
  data () {
    viewTransactions: false
    this.viewAllTransactions()
    return {
      headElements: ['Block Height', 'Timestamp', 'Harvester/Forger', 'Number of Transactions', 'Difficulty', 'Fees', 'Export CSV'],
      blockInfo: [],
      firstItemIndex: 0,
      lastItemIndex: 10
    }
  },
  methods: {
    viewAllTransactions: function (event = []) {
      _service.blockchainHttp.getBlockchainHeight().subscribe(
        next => {
          let total = null
          let heightWS = ''
          let totalHeight = ''
          _service.setBlocksHeightLocal(next)

          totalHeight = (event.length === 0) ? next.lower.toString() : event[event.length - 1].height.lower.toString()
          heightWS = totalHeight.slice(0, -2) + '01'
          total = (25 >= Number(totalHeight)) ? Number(heightWS) : Number(heightWS) - 100

          _service.blockchainHttp.getBlocksByHeightWithLimit(total, 100).subscribe(
            blockInfo => {
              blockInfo.forEach(element => {
                element['date'] = new Date(element.timestamp.compact() + (Deadline.timestampNemesisBlock * 1000)).toUTCString()
                if (event.length > 0) { event.push(element) }
              })

              this.blockInfo = (event.length === 0) ? blockInfo : event
              this.viewTransactions = true
              console.log(this.blockInfo)
              
            },
            error => {
              this.viewTransactions = false
              this.blockInfo = []
              this.viewAllTransactions()
            }
          )
        }
      )
    }
  }
}
</script>
