// src/app/explorer/components/recent-transactions/recent-transactions.component.ts
import { Component, OnInit, HostListener, ViewChild, ChangeDetectorRef, Input, AfterViewInit } from '@angular/core';
import { TransactionType } from 'proximax-nem2-sdk';
import { MdbTablePaginationComponent, MdbTableService } from 'ng-uikit-pro-standard';
import { AppConfig } from '../../../config/app.config';


@Component({
  selector: 'app-recent-transactions',
  templateUrl: './recent-transactions.component.html',
  styleUrls: ['./recent-transactions.component.scss']
})
export class RecentTransactionsComponent implements OnInit, AfterViewInit {

  @ViewChild(MdbTablePaginationComponent) mdbTablePagination: MdbTablePaginationComponent;
  searchText: string;
  firstItemIndex;
  lastItemIndex;
  previous: any;
  //
  dataSelected = {};
  nameTransaction = '';
  headElements = ['Timestamp', 'Amount', 'Fee',  'Sender', 'Recipient', 'View more'];
  typeTransaction = null;
  linkRoute = {
    explorerAccount: {
      'link': `/${AppConfig.routes.explorerAccount.split(':')[0]}`,
    }
  };
  arraTypeTransaction = {
    transfer: {
      id: TransactionType.TRANSFER,
      name: 'Transfer'
    },
    registerNameSpace: {
      id: TransactionType.REGISTER_NAMESPACE,
      name: 'Register namespace'
    },
    mosaicDefinition: {
      id: TransactionType.MOSAIC_DEFINITION,
      name: 'Mosaic definition'
    },
    mosaicSupplyChange: {
      id: TransactionType.MOSAIC_SUPPLY_CHANGE,
      name: 'Mosaic supply change'
    },
    modifyMultisigAccount: {
      id: TransactionType.MODIFY_MULTISIG_ACCOUNT,
      name: 'Modify multisig account'
    },
    aggregateComplete: {
      id: TransactionType.AGGREGATE_COMPLETE,
      name: 'Aggregate complete'
    },
    aggregateBonded: {
      id: TransactionType.AGGREGATE_BONDED,
      name: 'Aggregate bonded'
    },
    lock: {
      id: TransactionType.LOCK,
      name: 'Lock'
    },
    secretLock: {
      id: TransactionType.SECRET_LOCK,
      name: 'Secret lock'
    },
    secretProof: {
      id: TransactionType.SECRET_PROOF,
      name: 'Secret proof'
    }
  };

  @Input() elements = [];
  @HostListener('input') oninput() {
    this.mdbTablePagination.searchText = this.searchText;
  }

  constructor(
    private tableService: MdbTableService,
    private cdRef: ChangeDetectorRef
  ) { }

  ngOnInit() {
  }

  ngAfterViewInit() {
    this.mdbTablePagination.setMaxVisibleItemsNumberTo(100);
    this.firstItemIndex = this.mdbTablePagination.firstItemIndex;
    this.lastItemIndex = this.mdbTablePagination.lastItemIndex;

    this.mdbTablePagination.calculateFirstItemIndex();
    this.mdbTablePagination.calculateLastItemIndex();
    this.cdRef.detectChanges();
  }

  onNextPageClick(data: any) {
    this.firstItemIndex = data.first;
    this.lastItemIndex = data.last;
  }

  onPreviousPageClick(data: any) {
    this.firstItemIndex = data.first;
    this.lastItemIndex = data.last;
  }


  viewInfoTransaction(item, transaction) {
    const type = Object.keys(this.arraTypeTransaction).find(element => this.arraTypeTransaction[element].id === item['type']);
    console.log(type);
    this.dataSelected = transaction;
    this.nameTransaction = this.arraTypeTransaction[type].name;
    this.typeTransaction = item['type'];
  }

}

<ng-container>
  <div class="row mt-3rem">
    <div class="col-6">
      <h4>Recent transactions</h4>
      <h6>Account transactions</h6>
    </div>
  </div>

  <div class="table-responsive table-striped mt-1-5rem">
    <table mdbTable id="tablePreview" class="table table-hover table-bordered table-striped table-sm z-depth-0">
      <thead>
        <tr>
          <th *ngFor="let head of headElements; let i = index" scope="col" class="text-center"><b>{{head}}</b></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let item of elements; let i = index">
          <td class="th-lg text-center" *ngIf="i+1 >= firstItemIndex && i < lastItemIndex">
            <span class="fs-08rem fw-bolder">{{item?.deadline.value.toString()}}</span>
          </td>
          <td class="font-size-08rem text-center th-lg" *ngIf="i+1 >= firstItemIndex && i < lastItemIndex">
            <ng-container *ngIf="item?.mosaics !== undefined; else notAmount">
              {{item?.formattedAmount}}
            </ng-container>

            <ng-template #notAmount>
              0
            </ng-template>
          </td>
          <td class="font-size-08rem text-center th-lg" *ngIf="i+1 >= firstItemIndex && i < lastItemIndex">
            {{item?.fee.compact()}}
          </td>
          <td class="font-size-08rem text-center th-lg" *ngIf="i+1 >= firstItemIndex && i < lastItemIndex">
            <span class="font-size-08rem">
                <i *ngIf="item.type === arraTypeTransaction.transfer.id; else notRecipient" [ngStyle]="{'color': item.isSigner === true ? 'red' : 'green' }" style="padding-right: 10px;" class="fa fa-send" aria-hidden="true"></i>
                <a class="text-link mouse-pointer" [routerLink]="[linkRoute.explorerAccount.link, item.signer?.address['address']]" target="_blank">{{item.signer?.address.pretty()}}</a>
              </span>
          </td>
          <td class="font-size-08rem text-center th-lg" *ngIf="i+1 >= firstItemIndex && i < lastItemIndex">
            <ng-container *ngIf="item.type === arraTypeTransaction.transfer.id; else notRecipient">
              <span class="font-size-08rem">
                  <a class="text-link mouse-pointer" [routerLink]="[linkRoute.explorerAccount.link, item.recipient?.address]" target="_blank">{{item?.recipient.pretty()}}</a>
                </span>
            </ng-container>
            <ng-template #notRecipient>
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            </ng-template>
          </td>
          <td class="font-size-08rem text-align-center th-lg mouse-pointer" *ngIf="i+1 >= firstItemIndex && i < lastItemIndex" (click)="viewInfoTransaction(item, elements[i]); basicModal.show();">
            <i style="font-size: 18px; color: #118a81;" class="fa fa-search-plus" aria-hidden="true"></i>
          </td>
          <ng-container *ngTemplateOutlet="viewTypeTransfer; context:item"></ng-container>
        </tr>
      </tbody>
      <tfoot class="background-gris w-100">
        <tr>
          <td colspan="6">
            <mdb-table-pagination (nextPageClick)="onNextPageClick($event)" (previousPageClick)="onPreviousPageClick($event)">
            </mdb-table-pagination>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
</ng-container>

<div mdbModal #basicModal="mdbModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mybasicModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-notify modal-info modal-lg" role="document">
    <!--Content-->
    <div class="modal-content">
      <!--Header-->
      <div class="modal-header background-header">
        <p class="heading lead" style="font-weight: 500;">Transaction info</p>
        <button type="button" class="close" data-dismiss="modal" (click)="basicModal.hide()">
              <span aria-hidden="true" class="white-text">&times;</span>
          </button>
      </div>

      <!--Body-->
      <div class="modal-body w-w-b-w">
        <!-- TYPE TRANSFER -->
        <ng-container *ngIf="typeTransaction === arraTypeTransaction.transfer.id">
          <app-transfer-type [nameTransaction]=nameTransaction [dataSelected]=dataSelected [infoMosaic]=infoMosaic></app-transfer-type>
        </ng-container>

        <!-- REGISTER NAMESPACE -->
        <ng-container *ngIf="typeTransaction === arraTypeTransaction.registerNameSpace.id">
          <app-register-namespace [nameTransaction]=nameTransaction [dataSelected]=dataSelected></app-register-namespace>
        </ng-container>

        <!-- MOSAIC DEFINITION -->
        <ng-container *ngIf="typeTransaction === arraTypeTransaction.mosaicDefinition.id">
          <app-mosaic-definition [nameTransaction]=nameTransaction [dataSelected]=dataSelected></app-mosaic-definition>
        </ng-container>

        <!-- TYPE MOSAIC SUPPLY CHANGE -->
        <ng-container *ngIf="typeTransaction === arraTypeTransaction.mosaicSupplyChange.id">
          <app-type-mosaic-supply-change [nameTransaction]=nameTransaction [dataSelected]=dataSelected></app-type-mosaic-supply-change>
        </ng-container>

        <!-- TYPE MODIFY MULTISIG ACCOUNT -->
        <ng-container *ngIf="typeTransaction === arraTypeTransaction.modifyMultisigAccount.id">
          <app-modify-multisig-account [nameTransaction]=nameTransaction [dataSelected]=dataSelected></app-modify-multisig-account>
        </ng-container>

        <!-- AGGREGATE COMPLETE -->
        <ng-container *ngIf="typeTransaction === arraTypeTransaction.aggregateComplete.id">
          <app-aggregate-complete [nameTransaction]=nameTransaction [dataSelected]=dataSelected></app-aggregate-complete>
        </ng-container>

        <!-- AGGREGATE BONDED -->
        <ng-container *ngIf="typeTransaction === arraTypeTransaction.aggregateBonded.id">
          <app-aggregate-bonded [nameTransaction]=nameTransaction [dataSelected]=dataSelected></app-aggregate-bonded>
        </ng-container>
      </div>
    </div>
  </div>
</div>

// src/components/explorer/views/RecentTransactions.vue
<template>
  <div v-if="transactions.length !== 0">
    <div class="row mt-3rem">
      <div class="col-6">
        <h4>Recent transactions</h4>
        <h6>Account transactions</h6>
      </div>
    </div>
    <hr>
    <mdb-tbl striped responsiveXl responsiveLg responsiveMd responsiveSm>
      <mdb-tbl-head class="background-explorer" textWhite>
        <tr>
          <th v-for="(head, index) in headElements" :key="index" class="text-center">{{head}}</th>
        </tr>
      </mdb-tbl-head>
      <mdb-tbl-body>
        <tr v-for="(transaction, i) in transactions" :key="i">
          <td class="th-lg text-center" v-if="i+1 >= firstItemIndex && i < lastItemIndex">
            <span class="fs-08rem fw-bolder">{{transaction.deadline.value.toString()}}</span>
          </td>
          <td class="font-size-08rem text-center th-lg" v-if="i+1 >= firstItemIndex && i < lastItemIndex">
            <div v-if="transaction.mosaics !== undefined">
              {{transaction.formattedAmount}}
            </div>
            <div v-else>
              0
            </div>
          </td>
          <td class="font-size-08rem text-center th-lg" v-if="i+1 >= firstItemIndex && i < lastItemIndex">
            {{transaction.fee.compact()}}
          </td>
          <td class="font-size-08rem text-center th-lg" v-if="i+1 >= firstItemIndex && i < lastItemIndex">
            <span class="font-size-08rem">
              <i v-if="transaction.type === arraTypeTransaction.transfer.id"  style="padding-right: 10px;" :style="{'color': transaction.signer.publicKey === publicKeyAddress ? 'red' : 'green' }" class="fa fa-send" aria-hidden="true"></i>
              <a class="text-link mouse-pointer" target="_blank">{{transaction.signer.address.pretty()}}</a>
            </span>
          </td>
          <td class="font-size-08rem text-center th-lg" v-if="i+1 >= firstItemIndex && i < lastItemIndex">
            <div v-if="transaction.type === arraTypeTransaction.transfer.id">
              <span class="font-size-08rem">
                  <a class="text-link mouse-pointer" target="_blank">{{transaction.recipient.pretty()}}</a>
                </span>
            </div>
            <div v-else>
              ---
            </div>
          </td>
          <td class="font-size-08rem text-align-center th-lg mouse-pointer" v-if="i+1 >= firstItemIndex && i < lastItemIndex">
            <i style="font-size: 18px; color: #118a81;" class="fa fa-search-plus" aria-hidden="true"></i>
          </td>
        </tr>
      </mdb-tbl-body>
      <!-- <mdb-pagination circle>
        <mdb-page-item disabled>First</mdb-page-item>
        <mdb-page-nav prev disabled></mdb-page-nav>
        <mdb-page-item active>1</mdb-page-item>
        <mdb-page-item>2</mdb-page-item>
        <mdb-page-item>3</mdb-page-item>
        <mdb-page-item>4</mdb-page-item>
        <mdb-page-item>5</mdb-page-item>
        <mdb-page-nav next></mdb-page-nav>
        <mdb-page-item>Last</mdb-page-item>
      </mdb-pagination> -->
    </mdb-tbl>
  </div>
</template>

<script>
import { mdbTbl, mdbTblHead, mdbTblBody, mdbPagination, mdbPageItem, mdbPageNav } from 'mdbvue'
import { TransactionType } from 'proximax-nem2-sdk'
export default {
  name: 'RecentTransactions',
  props: {
    transactions: Array,
    publicKeyAddress: String
  },
  components: {
    mdbTbl,
    mdbTblHead,
    mdbTblBody,
    mdbPagination,
    mdbPageItem,
    mdbPageNav,
    mdbPageNav
  },
  data () {
    console.log(this.transactions)

    return {
      headElements: ['Timestamp', 'Amount', 'Fee',  'Sender', 'Recipient', 'View more'],
      firstItemIndex: 0,
      lastItemIndex: 10,
      arraTypeTransaction: {
        transfer: {
          id: TransactionType.TRANSFER,
          name: 'Transfer'
        },
        registerNameSpace: {
          id: TransactionType.REGISTER_NAMESPACE,
          name: 'Register namespace'
        },
        mosaicDefinition: {
          id: TransactionType.MOSAIC_DEFINITION,
          name: 'Mosaic definition'
        },
        mosaicSupplyChange: {
          id: TransactionType.MOSAIC_SUPPLY_CHANGE,
          name: 'Mosaic supply change'
        },
        modifyMultisigAccount: {
          id: TransactionType.MODIFY_MULTISIG_ACCOUNT,
          name: 'Modify multisig account'
        },
        aggregateComplete: {
          id: TransactionType.AGGREGATE_COMPLETE,
          name: 'Aggregate complete'
        },
        aggregateBonded: {
          id: TransactionType.AGGREGATE_BONDED,
          name: 'Aggregate bonded'
        },
        lock: {
          id: TransactionType.LOCK,
          name: 'Lock'
        },
        secretLock: {
          id: TransactionType.SECRET_LOCK,
          name: 'Secret lock'
        },
        secretProof: {
          id: TransactionType.SECRET_PROOF,
          name: 'Secret proof'
        }
      }
    }
  }

}
</script>
