// src/components/explorer/views/MosaicsInfo.vue
<template>
  <div>
    <div class="row mt-3rem">
      <div class="col-6">
        <h4>Mosaics info</h4>
      </div>
    </div>
    <hr>
    <mdb-tbl striped responsiveXl responsiveLg responsiveMd responsiveSm>
      <mdb-tbl-head class="background-explorer" textWhite>
        <tr>
          <th v-for="(head, index) in headElements" :key="index" class="text-center">{{head}}</th>
        </tr>
      </mdb-tbl-head>
      <mdb-tbl-body>
        <tr v-for="(mosaic, index) in mosaicsArray" :key="index">
          <td class="font-size-08rem text-align-center">
            <a class="text-link mouse-pointer">{{mosaic.nameMosaic}}</a>
          </td>
          <td class="font-size-08rem text-align-center">{{mosaic.properties.divisibility}}</td>
          <td class="font-size-08rem text-align-center">{{mosaic.properties.levyMutable}}</td>
          <td class="font-size-08rem text-align-center">{{mosaic.properties.supplyMutable}}</td>
          <td class="font-size-08rem text-align-center">{{mosaic.properties.transferable}}</td>
          <td *ngIf="viewAmount" class="font-size-08rem text-align-center">{{mosaic.formattedAmount}}</td>
          <td class="font-size-08rem text-align-center mouse-pointer th-lg">
            <i style="font-size: 18px; color: #118a81;" class="fa fa-search-plus" aria-hidden="true"></i>
          </td>
        </tr>
      </mdb-tbl-body>
    </mdb-tbl>
  </div>
</template>

<script>
import { mdbTbl, mdbTblHead, mdbTblBody } from 'mdbvue'

export default {
  name: 'MosaicsInfo',
  components: {
    mdbTbl,
    mdbTblHead,
    mdbTblBody
  },
  props: {
    mosaicsArray: Array,
    viewAmount: Boolean
  },
  created: function () {
    if (!this.viewAmount) {
      this.headElements = ['Name', 'Divisibility', 'Levy Mutable', 'Supply Mutable', 'Transferable', 'View More']
    } else {
      this.headElements = ['Name', 'Divisibility', 'Levy Mutable', 'Supply Mutable', 'Transferable', 'Quantity', 'View More']
    }
  }
}
</script>

// src/app/explorer/components/mosaics-info/mosaics-info.component.ts
import { Component, OnInit, Input, ViewChild } from '@angular/core';
import { MdbTableService } from 'ng-uikit-pro-standard';
import { AppConfig } from '../../../config/app.config';

@Component({
  selector: 'app-mosaics-info',
  templateUrl: './mosaics-info.component.html',
  styleUrls: ['./mosaics-info.component.scss']
})
export class MosaicsInfoComponent implements OnInit {

  @Input() mosaicsArray = [];
  @Input() viewAmount = false;
  searchText: string;
  headElements = [];
  // ********************
  linkRoute = {
    explorerAccount: {
      'link': `/${AppConfig.routes.explorerAccount.split(':')[0]}`
    },
    explorerBlock: {
      'link': `/${AppConfig.routes.explorerBlock.split(':')[0]}`
    },
    explorerMosaic: {
      'link': `/${AppConfig.routes.explorerMosaic.split(':')[0]}`,
    }
  };

  constructor(
  ) { }

  ngOnInit() {
    if (!this.viewAmount) {
      this.headElements = ['Name', 'Divisibility', 'Levy Mutable', 'Supply Mutable', 'Transferable', 'View More'];
    } else {
      this.headElements = ['Name', 'Divisibility', 'Levy Mutable', 'Supply Mutable', 'Transferable', 'Quantity', 'View More'];
    }
  }
}

<!-- MOSAICS -->
<div class="row mt-3rem">
  <div class="col-6">
    <h4>Mosaics info</h4>
  </div>
</div>

<div class="table-responsive table-striped ">
  <table mdbTable id="tablePreview" class="table table-hover table-bordered table-striped table-sm z-depth-0">
    <thead>
      <tr>
        <th *ngFor="let head of headElements" scope="col" class="text-align-center"><b>{{head}}</b></th>
      </tr>
    </thead>
    <tbody>
      <tr mdbTableCol *ngFor="let element of mosaicsArray; let i = index">
        <td class="font-size-08rem text-align-center">
          <a class="text-link mouse-pointer" [routerLink]="[linkRoute.explorerMosaic.link, element.nameMosaic]">{{element.nameMosaic}}</a>
        </td>
        <td class="font-size-08rem text-align-center">{{element.properties.divisibility}}</td>
        <td class="font-size-08rem text-align-center">{{element.properties.levyMutable}}</td>
        <td class="font-size-08rem text-align-center">{{element.properties.supplyMutable}}</td>
        <td class="font-size-08rem text-align-center">{{element.properties.transferable}}</td>
        <td *ngIf="viewAmount" class="font-size-08rem text-align-center">{{element.formattedAmount}}</td>
        <td class="font-size-08rem text-align-center mouse-pointer th-lg"
          [routerLink]="[linkRoute.explorerMosaic.link, element.nameMosaic]">
          <i style="font-size: 18px; color: #118a81;" class="fa fa-search-plus" aria-hidden="true"></i>
        </td>
      </tr>
    </tbody>
  </table>
</div>
