// src/app/explorer/components/info-transactions/type-mosaic-supply-change/type-mosaic-supply-change.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { NemProvider } from '../../../../shared/services/nem.provider';

@Component({
  selector: 'app-type-mosaic-supply-change',
  templateUrl: './type-mosaic-supply-change.component.html',
  styleUrls: ['./type-mosaic-supply-change.component.scss']
})
export class TypeMosaicSupplyChangeComponent implements OnInit {

  @Input() accountInfo = {};
  @Input() dataSelected = {};
  @Input() nameTransaction = '';

  constructor(
    private nemProvider: NemProvider
  ) { }

  ngOnInit() {
    this.nemProvider.mosaicHttp.getMosaicsName([this.dataSelected['mosaicId'].id]).subscribe(
      name => {
        this.accountInfo['nameMosaic'] = name[0].name;
      }
    );
  }

}

<div class="row">
  <div class="col-md-3">
    <span class="fs-08rem fw-bolder"><b>Type transaction:</b></span>
  </div>
  <div class="col-md-9">
    <span class="fs-08rem fw-bolder">{{nameTransaction}}</span>
  </div>
</div>
<hr>

<!-- MOSAIC INFO -->
<container>
  <div class="mt-3">
    <div class="row">
      <div class="col-md-3">
        <span class="fs-08rem fw-bolder"><b>Fee:</b></span>
      </div>
      <div class="col-md-9">
        <span class="fs-08rem fw-bolder">{{dataSelected?.fee.compact()}}</span>
      </div>
    </div>
  </div>

  <div class="mt-3">
    <div class="row">
      <div class="col-md-3">
        <span class="fs-08rem fw-bolder"><b>Mosaic:</b></span>
      </div>
      <div class="col-md-9">
        <span class="fs-08rem fw-bolder">{{accountInfo['nameMosaic']}}</span>
      </div>
    </div>
  </div>
  <hr>
</container>

<!-- SIGNER INFO -->
<container>
  <div class="mt-3">
    <div class="row">
      <div class="col-md-3">
        <span class="fs-08rem fw-bolder"><b>Signer:</b></span>
      </div>
      <div class="col-md-9">
        <span class="fs-08rem fw-bolder">{{dataSelected?.signer.publicKey}}</span>
      </div>
    </div>
  </div>
  <div class="mt-3">
    <div class="row">
      <div class="col-md-3">
        <span class="fs-08rem fw-bolder"><b>Signature:</b></span>
      </div>
      <div class="col-md-9">
        <span class="fs-08rem fw-bolder">{{dataSelected?.signature}}</span>
      </div>
    </div>
  </div>
  <hr>
</container>

<!-- TIMESTAMP & HASH INFO -->
<container>
  <div class="mt-3">
    <div class="row">
      <div class="col-md-3">
        <span class="fs-08rem fw-bolder"><b>Deadline:</b></span>
      </div>
      <div class="col-md-9">
        <span class="fs-08rem fw-bolder">{{dataSelected?.deadline.value.toString()}}</span>
      </div>
    </div>
  </div>
  <div class="mt-3">
    <div class="row">
      <div class="col-md-3">
        <span class="fs-08rem fw-bolder"><b>Hash:</b></span>
      </div>
      <div class="col-md-9">
        <span class="fs-08rem fw-bolder">{{dataSelected?.transactionInfo.hash}}</span>
      </div>
    </div>
  </div>
</container>

// src/components/explorer/views/infoTransactions/TypeMosaicSupplyChange.vue
<template>
  <div>
    <!-- FROM & TO INFO -->
    <mdb-row>
      <mdb-col md="3">
        <span class="fs-08rem fw-bolder"><b>Mosaic: </b></span>
      </mdb-col>
      <mdb-col md="9">
        <span class="fs-08rem fw-bolder">{{nameMosaic}}</span>
      </mdb-col>
    </mdb-row>
    <mdb-row>
      <mdb-col md="3">
        <span class="fs-08rem fw-bolder"><b>Fee:</b></span>
      </mdb-col>
      <mdb-col md="9">
        <span class="fs-08rem fw-bolder">{{transactionSelected.fee.compact()}}</span>
      </mdb-col>
    </mdb-row>
    <hr>
    <mdb-row>
      <mdb-col md="2">
        <span class="fs-08rem fw-bolder"><b>Duration:</b></span>
      </mdb-col>
      <mdb-col md="10">
        <span class="fs-08rem fw-bolder">{{transactionSelected.mosaicProperties.duration.compact()}}</span>
      </mdb-col>
    </mdb-row>
    <hr>
    <mdb-row>
      <mdb-col md="2">
        <span class="fs-08rem fw-bolder"><b>Signer: </b></span>
      </mdb-col>
      <mdb-col md="10">
        <span class="fs-08rem fw-bolder">{{transactionSelected.signer.publicKey}}</span>
      </mdb-col>
    </mdb-row>
    <mdb-row>
      <mdb-col md="2">
        <span class="fs-08rem fw-bolder"><b>Signature:</b></span>
      </mdb-col>
      <mdb-col md="10">
        <span class="fs-08rem fw-bolder">{{transactionSelected.signature}}</span>
      </mdb-col>
    </mdb-row>
    <hr>
    <mdb-row>
      <mdb-col md="2">
        <span class="fs-08rem fw-bolder"><b>Timestamp:</b></span>
      </mdb-col>
      <mdb-col md="10">
        <span class="fs-08rem fw-bolder">{{transactionSelected.deadline.value.toString()}}</span>
      </mdb-col>
    </mdb-row>
    <mdb-row>
      <mdb-col md="2">
        <span class="fs-08rem fw-bolder"><b>Height:</b></span>
      </mdb-col>
      <mdb-col md="10">
        <span class="fs-08rem fw-bolder">{{transactionSelected.transactionInfo.height.compact()}}</span>
      </mdb-col>
    </mdb-row>
    <mdb-row>
      <mdb-col md="2">
        <span class="fs-08rem fw-bolder"><b>Hash:</b></span>
      </mdb-col>
      <mdb-col md="10">
        <span class="fs-08rem fw-bolder">{{transactionSelected.transactionInfo.hash}}</span>
      </mdb-col>
    </mdb-row>
  </div>
</template>

<script>
import { mdbRow, mdbCol } from 'mdbvue'
import proximaxProvider from '@/services/proximaxProvider'
const _proximaxProvider = new proximaxProvider()

export default {
  name: 'TypeMosaicSupplyChange',
  components: {
    mdbRow,
    mdbCol
  },
  props: {
    transactionSelected: Object
  },
  data () {
    let name = this.getNameMosaic()
    return {
      nameMosaic: name
    }
  },
  methods: {
    getNameMosaic: function () {
      _proximaxProvider.mosaicHttp.getMosaicsName([this.transactionSelected.mosaicId.id]).subscribe(
        name => {
          return name[0].name
        }
      );
    }
  }
}
</script>
